import {ParticlesBackground} from "@/components/ui/backgrounds/particles";
import {Navbar} from "@/components/ui/navbar";
import type {Metadata} from "next";
import {Roboto, Roboto_Mono} from "next/font/google";
import "@/styles/global.css";
import {ReactNode} from "react";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jirre Verkerk - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // noinspection HtmlRequiredTitleElement
  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <script
        dangerouslySetInnerHTML={{
          __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
        }}
      />
    </head>
    <body className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}>
    <ParticlesBackground count={160} />

    <div className="fixed-clip-zone">
      <main className="max-w-7xl mx-auto flex flex-col items-center">
        <div className="h-22 w-full shrink-0 bg-transparent" aria-hidden="true" />

        <div className="w-full px-4 pt-8">
          {children}
        </div>
        <div className="grow" />
      </main>
    </div>

    <Navbar />
    </body>
    </html>
  );
}